In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

### Get default working data type in PyTorch

In [3]:
torch.get_default_dtype()

torch.float32

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

### Various tensor operations in PyThorch

In [6]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
torch.is_tensor(tensor_arr)

True

In [9]:
torch.numel(tensor_arr)

6

In [11]:
uninitialized = torch.Tensor(2,3)
uninitialized

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
random = torch.rand(2,2)
random

tensor([[0.3012, 0.0383],
        [0.7462, 0.1479]])

In [16]:
int_tensor = torch.Tensor([3,3]).type(torch.IntTensor)
int_tensor

tensor([3, 3], dtype=torch.int32)

In [18]:
short_tensor = torch.ShortTensor([1,3,5])
short_tensor

tensor([1, 3, 5], dtype=torch.int16)

In [19]:
half_tensor = torch.Tensor([3,3]).type(torch.half)
half_tensor

tensor([3., 3.], dtype=torch.float16)

In [24]:
tensor_full = torch.full((2,3),fill_value=10, dtype=torch.float)
tensor_full

tensor([[10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float32)

In [27]:
tensor_ones = torch.ones([4,4], dtype=torch.int32)
tensor_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [29]:
zeros_like = torch.zeros_like(tensor_ones)
zeros_like

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [30]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
tns = torch.rand(2,3)
tns

tensor([[0.8805, 0.5983, 0.6370],
        [0.3839, 0.9681, 0.6419]])

In [36]:
tns.fill_(10)
tns

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [37]:
# In place operation with '_'
tns.add_(5)
tns

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [38]:
tns.add(5)
tns

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [39]:
spc = torch.linspace(start=1.0, end=10.0, steps=30)
spc

tensor([ 1.0000,  1.3103,  1.6207,  1.9310,  2.2414,  2.5517,  2.8621,  3.1724,
         3.4828,  3.7931,  4.1034,  4.4138,  4.7241,  5.0345,  5.3448,  5.6552,
         5.9655,  6.2759,  6.5862,  6.8966,  7.2069,  7.5172,  7.8276,  8.1379,
         8.4483,  8.7586,  9.0690,  9.3793,  9.6897, 10.0000])

In [40]:
chunk = torch.chunk(spc,5,0)
chunk

(tensor([1.0000, 1.3103, 1.6207, 1.9310, 2.2414, 2.5517]),
 tensor([2.8621, 3.1724, 3.4828, 3.7931, 4.1034, 4.4138]),
 tensor([4.7241, 5.0345, 5.3448, 5.6552, 5.9655, 6.2759]),
 tensor([6.5862, 6.8966, 7.2069, 7.5172, 7.8276, 8.1379]),
 tensor([ 8.4483,  8.7586,  9.0690,  9.3793,  9.6897, 10.0000]))

In [43]:
torch.cat((chunk[1],chunk[4]),0)

tensor([ 2.8621,  3.1724,  3.4828,  3.7931,  4.1034,  4.4138,  8.4483,  8.7586,
         9.0690,  9.3793,  9.6897, 10.0000])

In [45]:
rand = torch.rand(3,3)
rand

tensor([[0.1156, 0.5198, 0.3628],
        [0.4514, 0.6906, 0.1341],
        [0.9998, 0.8625, 0.2045]])

In [46]:
rand[0][2]

tensor(0.3628)

In [48]:
rand[1:,1:]

tensor([[0.6906, 0.1341],
        [0.8625, 0.2045]])

In [49]:
rand.size()

torch.Size([3, 3])

In [50]:
rand.view(9)

tensor([0.1156, 0.5198, 0.3628, 0.4514, 0.6906, 0.1341, 0.9998, 0.8625, 0.2045])

In [51]:
transpose = torch.transpose(rand,0,1)
transpose

tensor([[0.1156, 0.4514, 0.9998],
        [0.5198, 0.6906, 0.8625],
        [0.3628, 0.1341, 0.2045]])

In [52]:
torch.sort(rand)

torch.return_types.sort(
values=tensor([[0.1156, 0.3628, 0.5198],
        [0.1341, 0.4514, 0.6906],
        [0.2045, 0.8625, 0.9998]]),
indices=tensor([[0, 2, 1],
        [2, 0, 1],
        [2, 1, 0]]))

In [54]:
abs = torch.abs(torch.Tensor([-5,-2,1,-7,4]))
abs

tensor([5., 2., 1., 7., 4.])

In [55]:
rand1 = torch.randn(2,3)
rand2 = torch.randn(2,3)

In [57]:
rand1 + rand2

tensor([[-0.2536,  2.0222, -1.4045],
        [-0.8781,  2.1920,  0.7058]])

In [58]:
torch.add(rand1,rand2)

tensor([[-0.2536,  2.0222, -1.4045],
        [-0.8781,  2.1920,  0.7058]])

In [60]:
torch.mul(rand1, rand2)

tensor([[-1.0923,  0.9340,  0.0951],
        [-0.8800,  1.1450, -0.0041]])

In [62]:
torch.clamp(torch.Tensor([[2,3,-5],[-4,-2,9]]),min=0,max=1)

tensor([[1., 1., 0.],
        [0., 0., 1.]])

In [63]:
t1 = torch.Tensor([3,4])
t2 = torch.Tensor([2,1])

In [64]:
torch.dot(t1,t2)

tensor(10.)

In [67]:
matrix = torch.Tensor([[1,2,3],[4,5,6]])
vector = torch.Tensor([9,8,7])

In [68]:
torch.mv(matrix,vector)

tensor([ 46., 118.])

In [72]:
another = torch.Tensor([[1],[2],[3]])
torch.mm(matrix, another)

tensor([[14.],
        [32.]])

In [73]:
ts = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
torch.argmin(ts,dim=1)

tensor([0, 0, 0])

In [74]:
torch.argmax(ts,dim=1)

tensor([2, 2, 2])

In [80]:
import numpy as np

In [81]:
tns = torch.randn(4,3)
tns

tensor([[-1.0649,  0.2659,  1.2686],
        [ 2.8719, -0.2544,  0.9905],
        [-0.8204,  0.1716,  1.5326],
        [ 0.7985, -1.5266, -0.8127]])

In [82]:
type(tns)

torch.Tensor

### Convert Tensor type to NumPy

In [83]:
nump = tns.numpy()
type(nump)

numpy.ndarray

In [84]:
torch.is_tensor(nump)

False

### Convert Numpy array to Tensor

In [85]:
arr = np.array([[1,2,3],[4,5,6]])
tns = torch.from_numpy(arr)
tns

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [86]:
arr[0][0]=999

In [87]:
tns

tensor([[999,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

In [88]:
tns1 = torch.as_tensor(arr)
tns1

tensor([[999,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

In [90]:
tns2 = torch.clone(tns1)
tns2[0][0]=888

In [91]:
tns2

tensor([[888,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

In [92]:
tns1

tensor([[999,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

### Check whether CUDA support is available

In [93]:
torch.cuda.is_available()

False

In [129]:
tt1 = torch.Tensor([[1,2,4]])
tt2 = torch.Tensor([[3],[2],[1]])
tt1.requires_grad

False

In [130]:
tt1.requires_grad_()

tensor([[1., 2., 4.]], requires_grad=True)

In [131]:
tt1.requires_grad

True

In [132]:
print(tt1.grad)

None


In [133]:
print(tt1.grad_fn)

None


In [138]:
op = torch.matmul(tt1,tt2)
op

tensor([[11.]], grad_fn=<MmBackward>)

In [139]:
op.requires_grad

True

In [140]:
print(op.grad_fn)

### Backward pass to calculate gradients and modify weights/biases accordingly

In [141]:
op.backward()

In [142]:
tt1.grad

tensor([[3., 2., 1.]])

In [144]:
print(tt2.grad)

None


In [145]:
with torch.no_grad():
    new_tt = tt1 * 2
    print(tt1.requires_grad)
    print(new_tt.requires_grad)

True
False
